<?php

namespace Yoda\EventBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUpcomingEvents($max = null){
        $qb= $this->createQueryBuilder('e')
            ->addOrderBy('e.time','ASC')
            ->andWhere('e.time>:now')
            ->setParameter('now', date('Y-m-d', strtotime("-8 days")));
             if ($max) {
                 $qb->setMaxResults($max);
             }

    return $qb
        ->getQuery()
        ->execute()
        ;
    }

    /**
     * @return mixed
     * @var Event []
     */
    public function getRecentlyUpdatedEvents(){
        $qb= $this->createQueryBuilder('e')
                   ->andWhere('e.time > :since')
                    ->setParameter('since',new \DateTime('-2 day'));
        return $qb
            ->getQuery()
            ->execute()
            ;
    }
}
